# Generated by Django 5.2 on 2025-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_rename_content_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
