services:
  - type: web
    name: newsbyte
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn newsbyte.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsbyte.settings
      - key: PYTHON_VERSION
        value: 3.11
    disk:
      name: media
      mountPath: /mnt/data
